Algoritmo "Variáveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Aprendendo o uso das variáveis
// Autor(a)    : Erick Fonseca
// Data atual  : 18/04/2020
Var
// Seção de Declarações das variáveis 
// primeiro nome
// segundo nome
// idade
// cidade
// endereço
   primeiroNome:, segundoNome, cidade, endereco: caractere
   idade: inteiro
   



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo